<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_TrafficLight" Id="{e1eec484-65f9-421c-8c30-11a3905070ac}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TrafficLight
VAR
    state : INT;  // 0=Red, 1=RedAmber, 2=Green, 3=Amber
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Step" Id="{02c72e4c-3c08-4536-b49f-c430bfb56785}">
      <Declaration><![CDATA[METHOD Step : INT
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE state OF
    0:
        state := 1;
    1:
        state := 2;
    2:
        state := 0;
    3:
        state := 0;
END_CASE;
Step := state;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>