<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_SchmittTriggerConsumer" Id="{890d6316-6981-48a6-bd44-01e20a89a47a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SchmittTriggerConsumer
VAR
    trigger : T1SchmittTrigger_Plc.FB_SchmittTrigger;
    bLastState : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[trigger(fInput := 0.5);
bLastState := trigger.Step();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>