<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CounterConsumer" Id="{f561e0c3-f2ca-4cff-902d-8728c72c678d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CounterConsumer
VAR
    counter : B2SignedDelta_Plc.FB_Counter;
    delta : DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[delta := UDINT_TO_DINT(counter.GetSignedDelta(a := 5, b := 7));
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>