<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_PipelineConsumer" Id="{8e8d5ab8-b7c6-49bc-8cad-53994c69c558}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PipelineConsumer
VAR
    stage : B4Pipeline_Plc.FB_PipelineStage;
    bStageError : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[stage(value := -1);
bStageError := stage.bError;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>