<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_TrafficLightConsumer" Id="{395df02d-4da9-44f7-9319-21dab7856a58}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TrafficLightConsumer
VAR
    light : B3TrafficLight_Plc.FB_TrafficLight;
    lastState : INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[lastState := light.Step();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>