<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_PIDControllerConsumer" Id="{7225539e-70b0-4b3f-b810-b7cb18fb252d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PIDControllerConsumer
VAR
    controller : B5PIDController_Plc.FB_PIDController;
    output : REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[controller(fError := 2.5);
output := controller.Step();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>