<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_SchmittTriggerConsumer" Id="{0575cae4-8b45-4f3b-a43a-366d9af87697}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SchmittTriggerConsumer
VAR
    trigger : T1SchmittTrigger_Plc.FB_SchmittTrigger;
    bLastState : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[trigger(fInput := 0.5);
bLastState := trigger.Step();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>