<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_TrafficLight" Id="{bbc8da29-dd17-49fe-bb76-9cd6f8ed87f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TrafficLight
VAR
    state : INT;  // 0=Red, 1=RedAmber, 2=Green, 3=Amber
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Step" Id="{97346fe1-2487-4375-a092-e1400fbe85ab}">
      <Declaration><![CDATA[METHOD Step : INT
CASE state OF
    0:
        state := 1;
    1:
        state := 2;
    2:
        state := 0;
    3:
        state := 0;
END_CASE;
Step := state;
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>