<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_RollingAverage" Id="{d3c8842e-30bf-45b6-80b0-1af7a42c9e79}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RollingAverage
VAR
    samples : ARRAY[0..15] OF INT;
    sampleCount : INT := 8;
    nextIndex : INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Step" Id="{bd5e6fc3-c885-4b2a-a2cf-e1e77985afae}">
      <Declaration><![CDATA[METHOD Step : INT
VAR_INPUT
    sample : INT;
END_VAR
VAR
    sum : DINT;
    i : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[samples[nextIndex] := sample;
nextIndex := (nextIndex + 1) MOD sampleCount;
sum := 0;
FOR i := 1 TO sampleCount DO
    sum := sum + samples[i];
END_FOR
Step := DINT_TO_INT(sum / sampleCount);
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>