<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Counter" Id="{3086daba-f4bd-45e6-88ad-83c11b2184d2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Counter
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetSignedDelta" Id="{a36f162b-75c1-4b02-9372-bbdbeb9b6b67}">
      <Declaration><![CDATA[METHOD GetSignedDelta : UDINT
VAR_INPUT
    a : INT;
    b : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[GetSignedDelta := DINT_TO_UDINT(INT_TO_DINT(a) - INT_TO_DINT(b));
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>