using System.Text;

namespace TcKit.Adapters.DocGen;

/// <summary>
/// Renders the GitHub Flavoured Markdown documentation pages, porting the Python Jinja templates
/// (<c>md_object.md</c>, <c>md_index.md</c>, <c>md_solution_index.md</c>).
/// </summary>
internal static class MarkdownRenderer
{
    private static readonly (string Key, string Label)[] s_sections =
    [
        ("function_block", "Function Blocks"), ("program", "Programs"), ("function", "Functions"),
        ("interface", "Interfaces"), ("gvl", "Global Variable Lists"), ("struct", "Structures"),
        ("enum", "Enumerations"),
    ];

    // -- Solution index -------------------------------------------------------

    internal static string SolutionIndex(ProjectDoc project)
    {
        var sb = new StringBuilder();
        sb.Append("# ").Append(project.Name).Append("\n\n*Generated by [TcKit](https://tckit.org)*\n\n## PLC projects\n\n");
        if (project.Plcs.Count > 0)
        {
            sb.Append("| PLC project | Objects |\n|------|---------|\n");
            foreach (var (_, plc) in project.Plcs.OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase))
            {
                sb.Append("| [").Append(plc.Name).Append("](").Append(plc.Name).Append("/index.md) | ")
                    .Append(plc.Objects.Count).Append(" |\n");
            }
        }
        else
        {
            sb.Append("*No PLC projects discovered in this solution.*\n");
        }

        return sb.ToString();
    }

    // -- Per-PLC index --------------------------------------------------------

    internal static string PlcIndex(PlcDoc plc)
    {
        var sb = new StringBuilder();
        sb.Append("# ").Append(plc.Name).Append("\n\n*Generated by [TcKit](https://tckit.org)*\n\n## Contents\n\n");
        foreach (var (key, label) in s_sections)
        {
            var objs = plc.Objects.Where(o => o.ObjType == key).ToList();
            if (objs.Count == 0)
            {
                continue;
            }

            sb.Append("### ").Append(label).Append("\n\n| Name | Description |\n|------|-------------|\n");
            foreach (var obj in objs)
            {
                var desc = obj.Comment.Description.Length > 0 ? RenderHelpers.Truncate(obj.Comment.Description, 100) : "";
                sb.Append("| [").Append(obj.Name).Append("](").Append(obj.Name).Append(".md) | ").Append(desc).Append(" |\n");
            }

            sb.Append('\n');
        }

        return sb.ToString();
    }

    // -- Object page ----------------------------------------------------------

    internal static string ObjectPage(ObjectDoc obj)
    {
        var sb = new StringBuilder();
        sb.Append("# ").Append(obj.Name).Append('\n');

        sb.Append("\n**Type:** ").Append(RenderHelpers.Title(obj.ObjType.Replace('_', ' ')));
        if (obj.Visibility.Length > 0)
        {
            sb.Append(" · **").Append(obj.Visibility).Append("**");
        }

        if (obj.IsAbstract)
        {
            sb.Append(" · *Abstract*");
        }

        if (obj.IsFinal)
        {
            sb.Append(" · *Final*");
        }

        if (obj.Extends.Length > 0)
        {
            sb.Append(" · **Extends:** [").Append(obj.Extends).Append("](").Append(obj.Extends).Append(".md)");
        }

        sb.Append('\n');

        if (obj.Implements.Count > 0)
        {
            sb.Append("\n**Implements:** ");
            sb.Append(string.Join(", ", obj.Implements.Select(i => $"[{i}]({i}.md)")));
            sb.Append('\n');
        }

        if (obj.Comment.Description.Length > 0)
        {
            sb.Append('\n').Append(obj.Comment.Description).Append('\n');
        }

        if (obj.Comment.Remarks.Length > 0)
        {
            sb.Append("\n> **Remarks:** ").Append(obj.Comment.Remarks).Append('\n');
        }

        sb.Append("\n---\n");

        AppendVarTable(sb, obj.Inputs, "Inputs");
        AppendVarTable(sb, obj.Inout, "In/Out (Bidirectional)");
        AppendVarTable(sb, obj.Outputs, "Outputs");

        if (obj.Variables.Count > 0)
        {
            if (obj.ObjType == "enum")
            {
                sb.Append("\n## Members\n\n| Name | Value | Description |\n|------|-------|-------------|\n");
                foreach (var v in obj.Variables)
                {
                    sb.Append("| `").Append(v.Name).Append("` | `").Append(v.VarType).Append("` | ").Append(v.Comment).Append(" |\n");
                }
            }
            else
            {
                var heading = obj.ObjType == "struct" ? "Fields" : obj.ObjType == "gvl" ? "Globals" : "Variables";
                sb.Append("\n## ").Append(heading).Append("\n\n");
                AppendVarTableBody(sb, obj.Variables);
            }

            sb.Append('\n');
        }

        if (obj.Methods.Count > 0)
        {
            sb.Append("\n## Methods\n\n");
            foreach (var method in obj.Methods)
            {
                sb.Append("### `").Append(method.Name).Append('`');
                if (method.ReturnType.Length > 0)
                {
                    sb.Append(" → `").Append(method.ReturnType).Append('`');
                }

                sb.Append('\n');

                var mods = new[] { method.Visibility, method.IsAbstract ? "ABSTRACT" : "", method.IsFinal ? "FINAL" : "" }
                    .Where(s => s.Length > 0);
                var modLine = string.Join(" ", mods);
                if (modLine.Length > 0)
                {
                    sb.Append("\n*").Append(modLine).Append("*\n");
                }

                if (method.Comment.Description.Length > 0)
                {
                    sb.Append('\n').Append(method.Comment.Description).Append('\n');
                }

                if (method.Inputs.Count > 0)
                {
                    sb.Append("\n**Parameters:**\n");
                    AppendVarTableBody(sb, method.Inputs);
                }

                if (method.Inout.Count > 0)
                {
                    sb.Append("\n**In/Out:**\n");
                    AppendVarTableBody(sb, method.Inout);
                }

                if (method.Comment.Returns.Length > 0)
                {
                    sb.Append("\n**Returns:** ").Append(method.Comment.Returns).Append('\n');
                }

                if (method.Body.Length > 0)
                {
                    sb.Append("\n```pascal\n").Append(method.Body).Append("\n```\n");
                }
            }
        }

        if (obj.Properties.Count > 0)
        {
            sb.Append("\n## Properties\n\n| Name | Type | Access | Description |\n|------|------|--------|-------------|\n");
            foreach (var prop in obj.Properties)
            {
                var access = prop.HasGet && prop.HasSet ? "GET/SET" : prop.HasGet ? "GET" : "SET";
                sb.Append("| `").Append(prop.Name).Append("` | `").Append(prop.ReturnType).Append("` | ").Append(access)
                    .Append(" | ").Append(prop.Comment.Description).Append(" |\n");
            }

            sb.Append('\n');
        }

        if (obj.Actions.Count > 0)
        {
            sb.Append("\n## Actions\n\n");
            foreach (var action in obj.Actions)
            {
                sb.Append("- `").Append(action).Append("`\n");
            }

            sb.Append('\n');
        }

        if (obj.UsedBy.Count > 0)
        {
            sb.Append("\n## Used by\n\n");
            foreach (var name in obj.UsedBy.OrderBy(n => n, StringComparer.Ordinal))
            {
                sb.Append("- [").Append(name).Append("](").Append(name).Append(".md)\n");
            }

            sb.Append('\n');
        }

        sb.Append("---\n\n## Declaration\n\n```pascal\n").Append(obj.Declaration).Append("\n```\n\n*Generated by [TcKit](https://tckit.org)*\n");
        return sb.ToString();
    }

    private static void AppendVarTable(StringBuilder sb, IReadOnlyList<VariableDoc> vars, string heading)
    {
        if (vars.Count == 0)
        {
            return;
        }

        sb.Append("\n## ").Append(heading).Append("\n\n");
        AppendVarTableBody(sb, vars);
        sb.Append('\n');
    }

    private static void AppendVarTableBody(StringBuilder sb, IReadOnlyList<VariableDoc> vars)
    {
        var hasDefaults = vars.Any(v => v.DefaultValue.Length > 0);
        if (hasDefaults)
        {
            sb.Append("| Name | Type | Default | Description |\n|------|------|---------|-------------|\n");
            foreach (var v in vars)
            {
                sb.Append("| `").Append(v.Name).Append("` | `").Append(v.VarType).Append("` | ")
                    .Append(v.DefaultValue.Length > 0 ? $"`{v.DefaultValue}`" : "").Append(" | ").Append(v.Comment).Append(" |\n");
            }
        }
        else
        {
            sb.Append("| Name | Type | Description |\n|------|------|-------------|\n");
            foreach (var v in vars)
            {
                sb.Append("| `").Append(v.Name).Append("` | `").Append(v.VarType).Append("` | ").Append(v.Comment).Append(" |\n");
            }
        }
    }
}
