<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CounterConsumer" Id="{0b35460f-ac8d-4d9b-88a2-22a92eae69ed}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CounterConsumer
VAR
    counter : B2SignedDelta_Plc.FB_Counter;
    delta : DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[delta := UDINT_TO_DINT(counter.GetSignedDelta(a := 5, b := 7));
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>