<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_PipelineStage" Id="{e54a5241-6129-4d57-96a3-a274d04e94dd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PipelineStage
VAR_INPUT
    value : INT;
END_VAR
VAR_OUTPUT
    bError : BOOL;
END_VAR
VAR
    inner : FB_PipelineInner;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Step" Id="{1a2d2250-826f-4e43-bad4-d885461d4cd0}">
      <Declaration><![CDATA[METHOD Step : INT
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[inner(value := value);
// MISSING: bError := inner.bError;
Step := value;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>