<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_PIDController" Id="{c484f452-a041-43ae-8da4-daa4d031efb6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PIDController
VAR_INPUT
    fError : REAL;
END_VAR
VAR_OUTPUT
    fOutput : REAL;
END_VAR
VAR
    fGain : REAL := 0.0;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Step" Id="{231e7c81-bdf7-403b-a524-742ee81ba1ba}">
      <Declaration><![CDATA[METHOD Step : REAL
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[fOutput := fError * fGain;
Step := fOutput;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>