<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_SchmittTrigger" Id="{c39c0c34-cb35-47af-b6a2-847e3a2e2173}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SchmittTrigger
VAR_INPUT
    fInput : REAL;
    fLowThreshold : REAL := 0.3;
    fHighThreshold : REAL := 0.7;
END_VAR
VAR_OUTPUT
    bState : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Step" Id="{a8c636f3-d0be-4cbf-8eba-f6a1227bce65}">
      <Declaration><![CDATA[METHOD Step : BOOL
;
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>