<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_PipelineStage" Id="{35f7af4f-b395-4d93-a833-4efff83808c3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PipelineStage
VAR_INPUT
    value : INT;
END_VAR
VAR_OUTPUT
    bError : BOOL;
END_VAR
VAR
    inner : FB_PipelineInner;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Step" Id="{8730aace-5bd3-4cce-8e91-62af765c74cd}">
      <Declaration><![CDATA[METHOD Step : INT
inner(value := value);
// MISSING: bError := inner.bError;
Step := value;
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>