<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_RollingAverageTests" Id="{049b8845-6af4-49c9-8552-395ef017c472}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RollingAverageTests EXTENDS TcUnit.FB_TestSuite
VAR
    averager : B1RollingAverage_Plc.FB_RollingAverage;
    result : INT;
    i : INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[AverageOfConstantStream();
]]></ST>
    </Implementation>
    <Method Name="AverageOfConstantStream" Id="{84356e3e-8b6c-4c86-a9d3-616d194168fe}">
      <Declaration><![CDATA[METHOD PRIVATE AverageOfConstantStream]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('AverageOfConstantStream');
FOR i := 1 TO 8 DO
    result := averager.Step(sample := 10);
END_FOR
AssertEquals_INT(
    Expected := 10,
    Actual := result,
    Message := 'Average of eight 10s should be 10');
TEST_FINISHED();
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>