<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TcKit.Core\TcKit.Core.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Reader\TcKit.Adapters.Reader.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Automation\TcKit.Adapters.Automation.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Ads\TcKit.Adapters.Ads.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Docs\TcKit.Adapters.Docs.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

