<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TcKit.Core\TcKit.Core.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Xml\TcKit.Adapters.Xml.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Analysis\TcKit.Adapters.Analysis.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Automation\TcKit.Adapters.Automation.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Ads\TcKit.Adapters.Ads.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.DocGen\TcKit.Adapters.DocGen.csproj" />
    <ProjectReference Include="..\TcKit.Adapters.Docs\TcKit.Adapters.Docs.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

